### ISSUE TITLE
Googlbot and Yandex are Missing

### ISSUE THREAD

**Issue by vanthome** [binarykitchen/spider-detector#1]
Hi,
although advertised differently, Googlebot is missing in the detection__!__
also I think yandex should be part of the detection.
Btw. I also think that this module should report google etc. as Spider because that's what the module is supposed to do.
BG

**Comment by binarykitchen** [comment]
well, googlebot is already included in the first regex at
https://github.com/binarykitchen/spider-detector/blob/master/index.js#L2

and it is being caught in the test at
https://github.com/binarykitchen/spider-detector/blob/master/test/direct.js#L15

but have just added yandex and published a new version.

reporting to google isn't scope of this package.
