### ISSUE TITLE
Why curl is recognized as a spider?

### ISSUE THREAD

**Issue by kevinprotoss** [binarykitchen/spider-detector#2]
Hi,

It's just a ulity, right? If some module such as `request`, sends some requests to the server, they should not be recognized as spider requests. Iff curl is used to send a request with definite `user-agent` like `googlebot`, then it's a spider request.

Bg,
Kevin

**Comment by binarykitchen** [comment]
you're right, stupid of me to treat curl as a spider. 

removed curl from the list and npm-published a new version.
