### ISSUE TITLE
Deploy latest version to NPM

### ISSUE THREAD

**Issue by JoeNyland** [binarykitchen/spider-detector#20]
Please can we get a new version of the package deployed to NPM which includes !16? We've been testing the changes for a few weeks now and don't see any issues with what's in the repo after !16 was merged, so a deploy from that point would be safe.

Many thanks 🙂

**Comment by binarykitchen** [comment]
Hi @JoeNyland - good question.

I'm pretty busy with kids. If you could do a pull request to bump Node/NPM, I'm happy to review it, and merge & publish next.

Thanks back,
M.

**Comment by JoeNyland** [comment]
Hi @binarykitchen Thanks, for getting back to me. I've just opened #21 which bumps the version for you. Thanks!

**Comment by binarykitchen** [comment]
Thanks, that's merged.

**Comment by JoeNyland** [comment]
Thanks. Could you push to NPM when you have a moment please?

**Comment by binarykitchen** [comment]
@JoeNyland done, published

**Comment by JoeNyland** [comment]
Thanks!
