### ISSUE TITLE
How to test it locally

### ISSUE THREAD

**Issue by pietro909** [binarykitchen/spider-detector#5]
Hi,
I need to try the `spider-detector` locally on my machine: how you do that? I mean, how you simulate a `spider`?

**Comment by binarykitchen** [comment]
@pietro909 have a look at https://github.com/binarykitchen/spider-detector/blob/master/index.js#L40

there you see it depends on the contents of `req.get('user-agent')` - you can fake a spider locally by setting a different user-agent in the request instance i think

**Comment by pietro909** [comment]
Super! thank you!
