### ISSUE TITLE
Request Hangs on app.use(detector.middleware())

### ISSUE THREAD

**Issue by apburton84** [binarykitchen/spider-detector#8]
When using the following:

    app.use(detector.middleware())

And after running ``npm start`` and when sending an HTTP request the request hangs until timeout

**Comment by apburton84** [comment]
It appears my error was to use:

    app.use(function(req, res, next) {
      if (req.isSpider()) {
        res.status(404).send('Not found');
      }
    });

Instead of:

    app.get('/', function(req, res, next) {
      if (req.isSpider()) {
        res.status(404).send('Not found');
      }
    });

How can I achieve the first i.e. ``app.use``

**Comment by binarykitchen** [comment]
it works fine for both, get() + use(). have just added more unit tests to cover this, see:
https://github.com/binarykitchen/spider-detector/blob/master/test/use.js

although i think your problem is that your blocking execution without using next():

```js
app.use(function(req, res, next) {
  if (req.isSpider()) {
    res.status(404).send('Not found');
  } // <--------- what happens here if it's not a spider???
});
```
